CR_PROMPT = """
#CONSTRUCTED RESPONSE (CR) ITEM PROMPT#

#CONTEXT#
You are designing a Constructed Response (CR) science assessment item for grade {grade}, aligned to the 3D NGSS framework (DCI, SEP, CCC). The CR must follow a Claim-Evidence-Reasoning (CER) structure and be solvable using only the information provided in the stimulus (for evidence) and the student’s own scientific knowledge (for reasoning). The stimulus must not include or hint at the claim or reasoning.

1. References (for item creation only)
1.1. 3D NGSS Reference: {ngss_ref}
1.2. DOK Levels Reference: {dok_ref}

2. Content Hierarchy
2.1. Standard: {standard}
2.2. What Students Will Do: {will_do}

3. Preliminary Work
3.1. Review the standard and Will-Do.
3.2. Identify 1–2 core scientific skills students need to demonstrate.
3.3. Ensure these skills reflect the DCI, SEP, CCC, and an appropriate DOK level.
3.4. Confirm:
- The claim must be independently generated by the student
- The evidence must be selected from the stimulus-provided data
- The reasoning must be based on the student’s scientific understanding

#FORMATTING REQUIREMENTS#
You must follow this exact structure:

Item X: CR: [Standard Code]
DCI: [DCI Code and Description]
Justification: Explain how the DCI is demonstrated in the reasoning students must apply.
SEP: [SEP Code and Short Name]
Justification: Explain how the SEP is required by asking students to construct explanations using data.
CCC: [CCC Code and Short Name]
Justification: Explain how the CCC shapes student reasoning or interpretation in this task.
DOK Level: [3 or 4 only]
Justification: Constructed Response (CER) items should be at DOK 3, as they require students to reason strategically, construct explanations, and synthesize information from the stimulus with scientific understanding. DOK 4 is acceptable only for extended tasks involving multi-step reasoning, integration of multiple sources, or cross-contextual transfer. DOK 1 is not permitted, and DOK 2 is rarely appropriate for CER-format CR items.

1. Standard
Include the full standard code and text.

2. Stimulus
Create a real-world, observable, and puzzling phenomenon described in 3–5 sentences. The stimulus must:
- Set up the need to model, explain, or analyze a scientific phenomenon
- Present qualitative or quantitative data that students can use as evidence
- Avoid including or hinting at the claim or reasoning
- Include a data table, diagram, graph, or short passage with clearly labeled variables or observations
- Use a student-friendly tone and developmentally appropriate language, avoiding technical jargon unless appropriate for the grade

3. Constructed Response Prompt (CER-Aligned)
Ask students to write a scientific explanation using the CER framework:
- Claim: Write a claim that answers the question.
- Evidence: Support your claim with two pieces of data from the stimulus.
- Reasoning: Use your own scientific knowledge to explain how your evidence supports your claim. Do not copy from the stimulus.

4. Performance-Level Rubric
Provide a 5-level CER rubric in a matrix format, using the following structure:
- Performance levels (Exceeding, Meeting, Developing, Approaching, Emerging) must appear as column headers
- CER components (Claim, Evidence, Reasoning) must appear as row headers
- Each cell should describe expected student performance for that component at that level
- Avoid point values
- Focus on:
--  Accuracy and clarity of the claim
-- Specificity and relevance of the evidence
-- Scientific correctness and depth of the reasoning
- The rubric should show progressive development across performance levels in both conceptual understanding and explanation quality

Example layout:
A table with three rows (Claim, Evidence, Reasoning) and five columns (Exceeding through Emerging). Each cell contains a clear description of expected student performance for that criterion and level.

5. Model Student Response (Exceeding Level)
Provide a complete CER response that meets the Exceeding level:
- The claim is scientifically accurate and fully responsive
- The evidence is well-selected and correctly cited from the stimulus
- The reasoning clearly connects the evidence to the claim using appropriate and grade-level scientific principles
- No part of the response should come directly from the stimulus unless it’s data being cited
"""