CR_PROMPT = """
#CONSTRUCTED RESPONSE (CR) ITEM PROMPT#

#CONTEXT#
You are designing a Constructed Response (CR) science assessment item for grade {grade}, aligned to the 3D NGSS framework (DCI, SEP, CCC). The CR must follow a Claim-Evidence-Reasoning (CER) structure and be solvable using only the information provided in the stimulus (for evidence) and the student’s own scientific knowledge (for reasoning). The stimulus must not include or hint at the claim or reasoning.

1. References (for item creation only)
1.1. 3D NGSS Reference: {ngss_ref}
1.2. DOK Levels Reference: {dok_ref}

2. Content Hierarchy
2.1. Standard: {standard}
2.2. What Students Will Do: {will_do}

3. Preliminary Work
3.1. Review the standard and Will-Do.
3.2. Identify 1–2 core scientific skills students need to demonstrate.
3.3. Ensure these skills reflect the DCI, SEP, CCC, and an appropriate DOK level.
3.4. Confirm:
- The claim must be independently generated by the student
- The evidence must be selected from the stimulus-provided data
- The reasoning must be based on the student’s scientific understanding

#FORMATTING REQUIREMENTS#
You must follow this exact structure:

Item X: CR: [Standard Code]
DCI: [DCI Code and Description]
Justification: Explain how the DCI is demonstrated in the reasoning students must apply.
SEP: [SEP Code and Short Name]
Justification: Explain how the SEP is required by asking students to construct explanations using data.
CCC: [CCC Code and Short Name]
Justification: Explain how the CCC shapes student reasoning or interpretation in this task.
DOK Level: [3 or 4 only]
Justification: Constructed Response (CER) items should be at DOK 3, as they require students to reason strategically, construct explanations, and synthesize information from the stimulus with scientific understanding. DOK 4 is acceptable only for extended tasks involving multi-step reasoning, integration of multiple sources, or cross-contextual transfer. DOK 1 is not permitted, and DOK 2 is rarely appropriate for CER-format CR items.

1. Standard
Include the full standard code and text.

2. Stimulus
Create a real-world, observable, and puzzling phenomenon described in 3–5 sentences. The stimulus must:
- Set up the need to model, explain, or analyze a scientific phenomenon
- Present qualitative or quantitative data that students can use as evidence
- Avoid including or hinting at the claim or reasoning
- Include a data table, diagram, graph, or short passage with clearly labeled variables or observations
- Use a student-friendly tone and developmentally appropriate language, avoiding technical jargon unless appropriate for the grade

3. Constructed Response Prompt (CER-Aligned)
Ask students to write a scientific explanation using the CER framework:
- Claim: Write a claim that answers the question.
- Evidence: Support your claim with two pieces of data from the stimulus.
- Reasoning: Use your own scientific knowledge to explain how your evidence supports your claim. Do not copy from the stimulus.

4. Performance-Level Rubric
Provide a 5-level CER rubric in a matrix format, using the following structure:
- Performance levels (Exceeding, Meeting, Developing, Approaching, Emerging) must appear as column headers
- CER components (Claim, Evidence, Reasoning) must appear as row headers
- Each cell should describe expected student performance for that component at that level
- Avoid point values
- Focus on:
--  Accuracy and clarity of the claim
-- Specificity and relevance of the evidence
-- Scientific correctness and depth of the reasoning
- The rubric should show progressive development across performance levels in both conceptual understanding and explanation quality

Example layout:
A table with three rows (Claim, Evidence, Reasoning) and five columns (Exceeding through Emerging). Each cell contains a clear description of expected student performance for that criterion and level.

5. Model Student Response (Exceeding Level)
Provide a complete CER response that meets the Exceeding level:
- The claim is scientifically accurate and fully responsive
- The evidence is well-selected and correctly cited from the stimulus
- The reasoning clearly connects the evidence to the claim using appropriate and grade-level scientific principles
- No part of the response should come directly from the stimulus unless it’s data being cited
"""

MC_PROMPT = """# MULTIPLE CHOICE (MC) ITEM PROMPT #

# CONTEXT #
You are creating a multiple-choice (MC) science assessment item for grade {grade}, grounded in the 3D NGSS framework (DCI, SEP, CCC) and aligned to the Depth of Knowledge (DOK) level appropriate for that grade.

## 1. References (for item creation only)
1.1. 3D NGSS Reference: {ngss_ref}  
1.2. DOK Levels Reference: {dok_ref}

## 2. Content Hierarchy
2.1. Standard: {standard}
2.2. What Students Will Do: {will_do}

## 3. Preliminary Work
3.1. Review the standard and Will Do.  
3.2. Identify 1–2 core scientific skills students need to demonstrate.  
3.3. Ensure these skills reflect the DCI, SEP, CCC, and an appropriate DOK level.

# FORMATTING REQUIREMENTS #
You must follow this exact structure and formatting:

Item X: MC: [Standard Code]

DCI: [DCI Code and Description]  
Justification: [1–2 sentences explaining how this DCI is demonstrated by student thinking in this item]

SEP: [SEP Code and Short Name]  
Justification: [1–2 sentences explaining how this SEP is required by the task]

CCC: [CCC Code and Short Name]  
Justification: [1–2 sentences explaining how this CCC shapes student reasoning in this item]

DOK Level: [1, 2, or 3]  
Justification: [1–2 sentences explaining why the thinking required aligns to this DOK level]

Stimulus:  
[A brief 1–2 sentence scenario that introduces a real-world phenomenon or situation relevant to the standard]  
[Visual Description: Describe any diagram, graph, model, or visual used. If no visual is included, omit this line.]

Question:  
[Write one clear question that targets a key concept or reasoning process]

A) [Option A]  
B) [Option B]  
C) [Option C]  
D) [Option D]

Answer: [Letter]

Rationale for correct choice(s):  
[Letter]) [Explain why the correct answer is scientifically valid and aligned with DCI, SEP, and CCC]

Rationale for incorrect choice(s):  
[Letter]) [Explain why each incorrect choice is wrong, referencing misconceptions, flawed reasoning, or misinterpretations of the stimulus or model]

# ITEM CREATION RULES #
- The item must assess reasoning or application, not recall.  
- The stimulus must be grounded in a real-world or observable phenomenon.  
- If a visual is included, it must serve a reasoning purpose (not decoration).  
- All language must be grade-appropriate and free of jargon.  
- Every answer option (A–D) must have a complete rationale.  
- Do NOT label any rationale as “Correct” or “Incorrect.”  
- Distractors must be scientifically plausible and based on:
  - Common student misconceptions  
  - Flawed logic tied to the SEP or CCC  
  - Misinterpretation of the model or stimulus  

# OPTIONAL EXAMPLE STRUCTURE (Do NOT copy directly—use as a structural model only) #
Item 1: MC: MS-LS2-1

DCI: LS2.A: Interdependent Relationships in Ecosystems  
Justification: The item assesses how changes in one population affect others in a food web, reflecting interdependence within ecosystems.

SEP: SEP2: Developing and Using Models  
Justification: Students interpret a food chain model to predict outcomes from population changes.

CCC: CCC4: Systems and System Models  
Justification: The food chain is a model representing a system. Understanding the system requires reasoning about how parts influence one another.

DOK Level: 2  
Justification: Students must use reasoning to interpret the model and predict changes, which requires more than recall but is not complex synthesis.

Stimulus:  
A diagram shows a pond food chain: algae → small fish → large fish → heron. A disease reduces the small fish population.  
[Visual Description: Arrow diagram of the pond food chain, with a red “X” over small fish.]

Question:  
What is the most likely effect on the pond ecosystem?

A) The algae population will increase.  
B) The large fish population will increase.  
C) The heron will eat more algae.  
D) The pond water will dry up.

Answer: A

Rationale for correct choice(s):  
A) With fewer small fish to eat them, algae populations would likely increase due to reduced predation.

Rationale for incorrect choice(s):  
B) Large fish depend on small fish; fewer small fish means their food source is limited.  
C) Herons don’t eat algae; this is not supported by the food chain.  
D) Water levels are unrelated to food web interactions in this context.
"""

MS_PROMPT = """# CONTEXT #
You are creating a set of science assessment items for grade {grade}, grounded in the 3D NGSS framework (DCI, SEP, CCC) and tailored to the Depth of Knowledge (DOK) levels appropriate to {grade}.

1. References (for prompt context only)  
1.1. 3D NGSS Reference: {ngss_ref}  
1.2. DOK Levels Reference: {dok_ref}

2. Content Hierarchy  
2.1. Standards: {standard}
2.2. What students will do (Will-Do): {will_do}

3. Preliminary Work
3.1. Review the standard and Will Do.  
3.2. Identify 1–2 core scientific skills students need to demonstrate.  
3.3. Ensure these skills reflect the DCI, SEP, CCC, and an appropriate DOK level.

# FORMATTING REQUIREMENTS #
- Number each item: “Item X:”  
- Specify item type (MS) and full standard code.  
- List DCI (code and description), must align with [standard].  
- SEP (code and short name) and justify it with 1–2 sentences.  
- CCC (code and short name) and justify it with 1–2 sentences.  
- State DOK Level and justify it with 1–2 sentences.  
- Use a real-world phenomenon or scenario as the stimulus.  
- If a visual is used, insert [Visual Description:] after the stimulus.  
- Write a clear single question for the stem.  
- Provide **five** answer choices.  
- At least **two** choices must be correct.  
- Include:  
  - Answer(s): [Letters]  
  - Rationale for each correct choice  
  - Rationale for each incorrect choice  
  - Do not label choices as “Correct” or “Incorrect.”

# ITEM CREATION GUIDELINES #
- Emphasize reasoning, evidence-based thinking, and 3D performance.  
- Avoid recall-only or trick questions.  
- Use grade-appropriate language and authentic contexts.  
- Include distractors that reflect common misconceptions or errors in reasoning.  
- Ensure that multiple correct choices are clearly defensible with the information provided.

# ITEM TYPES: 2. Multiple Select (MS) #
- Use DOK Level 2–3.  
- Provide all metadata and rationales per item.  
- Justify SEP, CCC, and DOK alignment.  
- Follow all distractor design and stimulus clarity rules.
"""

EBSR_PROMPT = """#EVIDENCE-BASED SELECTED RESPONSE (EBSR) ITEM PROMPT#

#CONTEXT#
You are designing an Evidence-Based Selected Response (EBSR) science item cluster for Grade {grade}, aligned to the 3D NGSS framework (DCI, SEP, CCC) and the appropriate Depth of Knowledge (DOK) levels.

This EBSR cluster includes:
- Two related phenomena (Part 1 and Part 2)
- Four total items (two per part):

Part 1
- Stimulus: Phenomenon 1 (5–6 sentences)
- Item 1: Multiple Choice (MC) – Claim selection
- Item 2: Multiple Select (MS) – Evidence selection (select 2 of 5)

Part 2
- Stimulus: Phenomenon 2 (5–6 sentences, related but not identical)
- Item 3: Multiple Choice (MC) – Reasoning explanation
- Item 4: Multiple Choice (MC) – Application or prediction

1. References (for item creation only)
1.1. 3D NGSS Reference: {ngss_ref}
1.2. DOK Levels Reference: {dok_ref}

2. Content Hierarchy
2.1. Standard: {standard}
2.2. What Students Will Do: {will_do}

3. Preliminary Work
3.1. Review the standard and Will-Do.
3.2. Identify 1–2 core scientific skills students need to demonstrate.
3.3. Ensure these skills reflect the DCI, SEP, CCC, and an appropriate DOK level.

#STIMULUS FORMAT#
Part 1: Phenomenon
Write a 5–6 sentence paragraph describing a real-world, observable scientific phenomenon. It should involve:
- Measurable changes or interactions
- Relationships in systems, organisms, or environments
- Enough detail to support claim and evidence reasoning (Items 1 and 2)

If using a visual, include the following:

Visual Description:
Write a detailed, sensory-rich description of a labeled diagram, graph, or model. Be precise and instructional, like describing a simulation to a developer. Specify:
- Axes, units, labels, colors, flows, spatial layout
- Movement, changes over time, interactions

Part 2: Continued Phenomenon
Write another 5–6 sentence paragraph that continues the scenario. This must:
- Be clearly related but not identical to Part 1
- Introduce a system change, human intervention, or environmental shift
- Provide reasoning context for Items 3 and 4

Include an updated Visual Description if needed (e.g., new conditions, populations, treatment areas, etc.).
#ITEM FORMAT (USE FOR EACH ITEM)#
Item X: [Type]: [Standard Code]
DCI: [Code and Description]
Justification: [How the concept is demonstrated]
SEP: [Code and Name]
Justification: [How students engage with this practice]
CCC: [Code and Name]
Justification: [How this shapes the reasoning task]
DOK Level: [1–4]
Justification: [Why this level applies]

Stimulus:
[Copy the relevant Part 1 or Part 2 stimulus]

Visual Description:
[Only if used; include full descriptive detail]

Question:
[Write a clear, grade-appropriate question]

A) [Option A]
B) [Option B]
C) [Option C]
D) [Option D]
E) [Option E] (MS only)

Answer(s): [Correct letter(s)]

Rationale for A:
[Explain reasoning or flaw]
Rationale for B:
[...]
Rationale for C:
[...]
Rationale for D:
[...]
Rationale for E:
[...] (only for MS)

#ITEM TYPE GUIDANCE#
Part 1 – Item 1: MC – Claim
- Ask for the most accurate scientific claim based on Phenomenon 1.

Part 1 – Item 2: MS – Evidence
- Ask for two valid pieces of evidence supporting the claim. Provide 5 total choices.

Part 2 – Item 3: MC – Reasoning
- Ask students to explain how or why the system behaves based on the continued scenario.

Part 2 – Item 4: MC – Application
- Ask students to predict the outcome or evaluate the impact of a solution or change in Part 2. Aim for DOK 3–4.

#ITEM WRITING RULES#
1. Each stimulus must be 5–6 sentences
2. Visuals must support reasoning and be described with precision
3. All MC and MS items must include:
- DCI, SEP, CCC, and DOK metadata with 1–2 sentence justifications
- A complete rationale for every answer option
4. Do NOT assess recall-only content
5. Distractors must be based on:
- Common student misconceptions
- Flawed logic or reasoning
- Misinterpretation of models or stimulus
"""

TE_PROMPT = """
# CONTEXT
You are creating a Technology-Enhanced (TE) science assessment item set for Grade {grade}, grounded in the 3D NGSS framework (DCI, SEP, CCC) and aligned to the Depth of Knowledge (DOK) level appropriate for that grade.

Each standard provided below must have one TE item for each of the following interaction subtypes:
- Drag-and-Drop
- Hot Spot (click to identify)
- Inline Choice (dropdown)
- Graphing or Model Construction

This will result in 4 items per standard.

## 1. References (for prompt context only)
- 3D NGSS Reference: {ngss_ref}
- DOK Levels Reference: {dok_ref}

## 2. Content Hierarchy
- Standard: {standard}
- What students will do (Will-Do): {will_do}

## 3. Preliminary Steps
1. Review the Standards and Will-Do
2. Select 1 real-world phenomenon or system per standard that lends itself to all 4 TE subtypes
3. Map each interaction type to a reasoning task aligned to the standard and DOK level
4. For each interaction type, ensure the task emphasizes 3D NGSS integration and results in a clearly scorable output
5. Use phenomena, simulations, or diagrams that are grade-appropriate and instructionally meaningful

---

## 4. ITEM FORMAT (Use for Each of the 4 Items Per Standard)

 4.1. Item Header
- Item X: TE - {{interaction_type}}: {{standard_code}}
- DCI: {{dci_code}} – {{dci_description}}
- SEP: {{sep_code}} – {{sep_name}}
- Justification: {{sep_justification}}
- CCC: {{ccc_code}} – {{ccc_name}}
- Justification: {{ccc_justification}}
- DOK Level: {{dok_level}}
- Justification: {{dok_justification}}

4.2. Stimulus
1. Phenomenon or Scenario: Write a 3–4 sentence stimulus that introduces the phenomenon in a relatable, real-world context. The writing should:
- Be student-friendly and grade-appropriate
- Describe a simple event or observation involving the phenomenon, not the explanation.
- Reflect everyday experiences, classroom labs, or media-based curiosity.
- Avoid technical terms unless they appear naturally (e.g., ‘carbon dioxide’ instead of ‘CO₂’ unless contextually relevant).
- End in a way that sets up the need to model, analyze, or explain what’s happening.
- Use second-person (“you”) or third-person (“a class,” “a student”) to keep it engaging.
- Ensure all information necessary to answer the item is present in the stimulus and/or visual; avoid requiring outside knowledge beyond grade-level expectations.

2. Visual Description: Describe a labeled diagram, model, graph, or visual zone. Ensure it directly supports the student task.
- Write a detailed visual description for a technology-enhanced science assessment item. The description should go beyond basic labels and provide a fully immersive, sensory-rich representation of the visual stimulus.
- The tone should be precise, vivid, and instructional — like you're describing a screenshot for an item developer or simulation engineer. Do not leave anything to assumption.

4.3. Task Prompt
Provide a directive that aligns with the interaction type:
1. Drag-and-Drop: "Drag each label to the correct part of the system to show…"
- Define both draggable items and labeled drop targets.
2. Hot Spot: "Click on the part of the diagram/system that shows…"
- Define clickable zones and what constitutes a correct selection.
3. Inline Choice: "Use the dropdowns to complete the explanation/model that best describes…"
- Embed dropdowns in a meaningful explanation or visual; define each option and correct choice.
4. Graphing: "Plot the data from the table to show…"
- Define the x/y axes, graph type, variables, or parts of the model to be constructed.

All prompts must clearly state the task and align to specific scientific reasoning.

4.4. Correct Response and Scoring
- Correct Response Criteria: Explicitly define what a correct answer looks like for the interaction type (labels, click zones, dropdown choices, plotted data, or model elements).
- Scoring Rule: Specify how full credit and partial credit are awarded.
- Scientific Rationale: Provide a brief explanation of why the correct response is scientifically valid, using 3D reasoning (DCI + SEP + CCC).
- Distractor Rationale: Identify the most likely incorrect responses and explain the misconception or error in reasoning they reflect.

5. GENERAL REQUIREMENTS FOR ALL ITEMS
All four interaction types must be instructionally necessary and tied to the SEP or CCC reasoning in the standard
- Do not reuse a multiple-choice item format disguised as TE
- All interactions must be auto-scorable or clearly rubric-scored
- Visuals, simulations, or diagrams must be necessary for completing the task (not decorative)
- Inline Choice items should never be vague; dropdowns must be embedded in rich context and scaffold reasoning
- All items must be answerable using only the information provided in the stimulus and visual. Do not assume students have prior knowledge beyond what is introduced in the text or diagram

6. REPEAT FOR EACH STANDARD
For each standard:
- Create 4 items using the format above
- Number each sequentially (e.g., Item 1, Item 2, ...)
- All items must share a common phenomenon but focus on different reasoning tasks
"""